version: "1.0" # optional since v1.27.0

services:
  backend:
    container_name: backend-node-app
    image: tnson/backend-node-app:latest
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 8000:8080
    environment:
      - SERVER_PORT=8080
    volumes:
      - ./api:/app
  frontend:
    stdin_open: true
    tty: true
    container_name: weather-app
    image: tnnson/weather-app:latest
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - REACT_APP_BE_URL=http://localhost:8000
